### ISSUE TITLE
Heartbeat

### ISSUE THREAD

**Issue by CryptXor** [CrackAttackz/JetBrainsLicenseServer#1]
First off, all product activation's work.
Secondly great work.
Thirdly, and I am not sure if it is true for other products, but ReSharper needs a constant heartbeat in order to keep the license valid. If a connection has not been established within 48 hours from the last heartbeat the license is invalidated. I am working on coding a background service to deal with that issue.

**Comment by CrackAttackz** [comment]
Thanks! I'm looking into the ReSharper thing. I added in a handler for the "ping.action" request, but I found for the IDEs at least that only seems to apply to the Discover server button.

According to their documentation, you're right about the 48 hour thing:

```
Ticket Revocation Period (s): every client with a floating ticket must send a prolongation message to the server after a certain period of time has passed. You can specify that period in seconds in this field. If the client does not prolong its ticket within the revocation period (e.g. due to power outage or unexpected crash), the ticket will be revoked by the server and added to the pool of free tickets. The client that held the ticket, will have to re-obtain the new ticket. If the server is offline at the time the client attempts to prolong the ticket, it is up to the client how to handle this situation. All current clients usually tolerate server absence for some time (48 hours). If server is still offline after 48 hours, the client will ask for a license again.
```

**Comment by CryptXor** [comment]
:ok:

**Comment by CrackAttackz** [comment]
Tested Release 1.1 with ReSharper and it works at licensing all of those with the ping implementation:

![Licenses Obtained](http://i.imgur.com/X2t66a7.png)

If the license server isn't running, ReSharper appears to allow the license to be used for the next 48 hours. It's probably best if the license server is just always running in the background as it likes to ping quite a bit.

Looks like you can tell @swell he can use the latest release.
