### ISSUE TITLE
<CLCGenomicsWorkbench>

### ISSUE THREAD

**Issue by Binarygate** [CrackAttackz/JetBrainsLicenseServer#2]
Hi CrackAttackz, your work on https://github.com/CrackAttackz/JetBrainsLicenseServer is gr8t , infact i love it.
I discovered your approach was thru the licence server great work. 
i have challenge with a soft <CLCGenomicsWorkbench> http://www.clcbio.com/products/clc-genomics-workbench/ please take a look at this 
. i will be earnestly waiting for a reply. 
Thanks
Binarygate

**Comment by CrackAttackz** [comment]
I'll take a look when I have some time.

**Comment by Binarygate** [comment]
thanks
